version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - logging-wrapper_logging-wrapper

volumes:
  timescale_data:

networks:
  logging-wrapper_logging-wrapper:
    external: true
